# Generated by Django 6.1 on 2026-08-30 16:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuteCorridor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('origin_hub', models.CharField(max_length=150)),
                ('destination_hub', models.CharField(max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=2, default=18.5, max_digits=6)),
                ('estimated_minutes', models.PositiveIntegerField(default=28)),
                ('frequency_minutes', models.PositiveIntegerField(default=15)),
                ('base_fare', models.DecimalField(decimal_places=2, default=8.5, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_uid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('corporate', 'Corporate Commuter')], db_index=True, default='passenger', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommuterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_pickup_hub', models.CharField(blank=True, default='Central Station Transit Hub', max_length=150)),
                ('preferred_dropoff_hub', models.CharField(blank=True, default='Tech Corridor West Gate', max_length=150)),
                ('preferred_commute_time', models.CharField(blank=True, default='08:30 AM', max_length=50)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('subscription_status', models.CharField(choices=[('active', 'Active Subscription'), ('paused', 'Paused'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('carbon_savings_kg', models.DecimalField(decimal_places=2, default=14.5, max_digits=8)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Veloce Enterprise Corp', max_length=150)),
                ('corporate_domain', models.CharField(default='veloce.global', max_length=100)),
                ('employee_id', models.CharField(blank=True, default='EMP-7701', max_length=50)),
                ('department', models.CharField(default='Engineering & Product', max_length=100)),
                ('monthly_transit_subsidy', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('subsidy_used_this_month', models.DecimalField(decimal_places=2, default=45.0, max_digits=8)),
                ('is_corporate_verified', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(default='Tesla', max_length=60)),
                ('vehicle_model', models.CharField(default='Model Y', max_length=60)),
                ('vehicle_year', models.PositiveIntegerField(default=2024)),
                ('vehicle_color', models.CharField(default='Obsidian Black', max_length=30)),
                ('license_plate', models.CharField(default='VEL-2049', max_length=20)),
                ('seating_capacity', models.PositiveSmallIntegerField(default=4)),
                ('driver_license_number', models.CharField(blank=True, default='DL-9843210', max_length=50)),
                ('is_driver_approved', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=4.95, max_digits=3)),
                ('total_trips_completed', models.PositiveIntegerField(default=128)),
                ('earnings_balance', models.DecimalField(decimal_places=2, default=420.75, max_digits=10)),
                ('current_corridor', models.CharField(default='Express Corridor A-12 (North <-> South Tech Line)', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
